[package]
name = "rudoku"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
fakeit = "1.4.1"
itertools = "0.14.0"
ratatui = "0.30.0"
unicode-width = "0.2.2"
